import { getSession } from "next-auth/react";
import Head from "next/head";
import Feeds from "../components/Feeds";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { db } from "../firebase";

export default function Home({ data: session, posts }) {
  return (
    <>
      <Head>
        <title>Facebook clone - Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://links.papareact.com/5me" />
      </Head>

      {!session ? (
        <Login />
      ) : (
        <div className="h-screen bg-gray-100 overflow-hidden">
          <Header userImage={session.user.image} userName={session.user.name} />

          <main className="flex">
            <Sidebar
              userImage={session.user.image}
              userName={session.user.name}
            />
            <Feeds posts={posts} />
            <Widgets />
          </main>
        </div>
      )}
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  //get the user
  const session = await getSession(ctx);

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));

  return {
    props: {
      data: session,
      posts: docs,
    },
  };
};
